# Generated by Django 4.2 on 2026-04-06 12:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('ride_datetime', models.DateTimeField()),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ride_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger'), ('both', 'Both')], default='passenger', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rides.ride')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['from_location'], name='rides_ride_from_lo_66f647_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['to_location'], name='rides_ride_to_loca_2ee9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['ride_datetime'], name='rides_ride_ride_da_430414_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_ride_status_b1560e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ride', 'status'], name='rides_booki_ride_id_c97331_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passenger'], name='rides_booki_passeng_25d275_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('ride', 'passenger')},
        ),
    ]
