# Generated by Django 4.2 on 2026-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
