# Generated by Django 4.2 on 2026-04-22 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_car_name_ride_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunSQL(
            "UPDATE rides_ride SET departure_datetime = ride_datetime, arrival_datetime = ride_datetime",
            reverse_sql="UPDATE rides_ride SET ride_datetime = departure_datetime"
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_datetime',
        ),
    ]
