# Generated by Django 4.2 on 2026-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_add_seats_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-departure_datetime']},
        ),
        migrations.AddField(
            model_name='ride',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['departure_datetime'], name='rides_ride_departu_5225f2_idx'),
        ),
    ]
